# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Agent01

variables:
  JAVA_HOME: '/usr/bin/java'

steps:
- script: |
    echo "##vso[task.setvariable variable=PATH]$JAVA_HOME/bin:$PATH"
  displayName: 'Set Java Path'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

